### ISSUE TITLE
maxviews error

### ISSUE THREAD

**Issue by danmarsden** [danielneis/moodle-availability_maxviews#1]
I guess this is related to your comment about legacy logs (I have them enabled)

error converting legacy event data Error reading from databaseERROR: column "contextid" does not exist LINE 1: SELECT COUNT('x') FROM mdl_log WHERE contextid = $1 AND user... ^ SELECT COUNT('x') FROM mdl_log WHERE contextid = $1 AND userid = $2 AND crud = $3 [array ( 0 => 1623, 1 => '2', 2 => 'r', )]
line 166 of /admin/tool/log/store/legacy/classes/log/store.php: call to debugging()
line 97 of /availability/condition/maxviews/classes/condition.php: call to logstore_legacy\log\store->get_events_select_count()
line 84 of /availability/classes/condition.php: call to availability_maxviews\condition->is_available()
line 265 of /availability/classes/tree.php: call to core_availability\condition->check_available()
line 197 of /availability/classes/info.php: call to core_availability\tree->check_available()

**Comment by danmarsden** [comment]
- I got that particular error when using the lesson module and with legacy logs enabled.

**Comment by danielneis** [comment]
Hi, @danmarsden 

I've made some Behat tests with the Lesson module and for Moodle 3.0 it does work with the default settings:
https://travis-ci.org/danielneis/moodle-availability_maxviews/jobs/124310145

I am closing this issue as it may be resolved or Moodle 3.0 does not enables legacy log by default, so it may not be required to be supported by the plugin.

Kind regards,
Daniel

**Comment by danmarsden** [comment]
great! :-)
