### ISSUE TITLE
opening a pull request

### ISSUE THREAD

**Issue by fmido88** [danielneis/moodle-availability_maxviews#12]
hey @danielneis 
I made a pull request which modify some of the last code, I hope you merge it.
It fixes two error, one with upgrade.php and the other for duplicating data in the database when calling get_record().
and modified it a little bit for allowing to select multiple users and make the value from the form is additional value.

I finished working on a block that when added to a course it display the limitation of the views to users and the remaining views form them.

https://github.com/fmido88/moodle-block_maxviews

**Comment by danielneis** [comment]
thank you for the fixes, I've reviewed you patch and it looks good but need some fixes as well. I kept the pull request open but I'll close this issue.

**Comment by fmido88** [comment]
Thanks, I'll working on issues you told me about and update the fork.
