### ISSUE TITLE
Restriction causes an Exception if placed on a section

### ISSUE THREAD

**Issue by Badatos** [danielneis/moodle-availability_maxviews#16]
Hello,
We just detected a bug causing your plugin preventing a course to be displayed at all, displaying this Exception :

```
Error
Exception : Call to undefined method core_availability\info_section::get_course_module()
```

How to reproduce :
* Add a maxviews restriction access on a section in a course on Moodle >= 4.0

**Comment by danielneis** [comment]
thank you for the fix!
