### ISSUE TITLE
PHP notice Trying to get property of non-object

### ISSUE THREAD

**Issue by mudrd8mz** [danielneis/moodle-availability_maxviews#5]
With the plugin installed, when I add a new Workshop instance (thought I guess it will be the same case with any module) via the /course/modedit.php file, I get

```
Notice: Trying to get property of non-object in 
/availability/condition/maxviews/classes/frontend.php on line 49
```

**Comment by danielneis** [comment]
looks like $cm (cm_info) is null when adding a new module.
is there any other way to know which type of module is being added or if is a section?
