### ISSUE TITLE
Reset students views

### ISSUE THREAD

**Issue by operatorone** [danielneis/moodle-availability_maxviews#7]
Hi Daniel, thanks for the great extension. I got a question concerning the views. Is there a way to reset the views if a student mssed it up accident and give him another chance? Therefore the views have to be deleted I assume, but do you have a hint for me?

Cheers, Til

**Comment by fmido88** [comment]
I need this option too

**Comment by fmido88** [comment]
I created a simple block plugin to do so, choosing the student enrolled to a course, and a module and increse the limit for this student only for this module

I'll try to upload it soon along with the customization of this plugin to make it work with the mentioned block with a pull-request
I'm new to development and can't use github very well yet

If you want you can get them from the drive [here](https://drive.google.com/drive/folders/1xFRrOp9f2rx5zgKelIZcHhQQv0Ht7dtp)  or you can wait till I upload both of them here

**Comment by fmido88** [comment]
Created a pull request, I hope to be merged, and the block is available here:
https://github.com/fmido88/moodle-block_resetviews

**Comment by fmido88** [comment]
@danielneis thanks for the update, I'll try it
